import type {
  VerificationProfile,
  VerificationProfileId,
  VerificationSignal,
} from "./verification-profile-types";

export const PROFILES: Record<VerificationProfileId, VerificationProfile> = {
  "bun-unit": {
    id: "bun-unit",
    label: "Bun/Vitest unit regression",
    command: "bun run test",
    sourceType: "builtin",
    packageName: null,
    executable: "bun",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: true,
    riskTier: "low",
    installHint: null,
  },
  doctor: {
    id: "doctor",
    label: "UT-TDD doctor hard gate",
    command: "bun run src/cli.ts doctor",
    sourceType: "builtin",
    packageName: null,
    executable: "bun",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: true,
    riskTier: "low",
    installHint: null,
  },
  "mcp-inspector-smoke": {
    id: "mcp-inspector-smoke",
    label: "MCP Inspector tools/list smoke",
    command: "ut-tdd mcp inspect <name> --method tools/list",
    sourceType: "mcp",
    packageName: "@modelcontextprotocol/inspector",
    executable: "bun",
    authEnv: [],
    requiresNetwork: true,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "bun add -D @modelcontextprotocol/inspector",
    sourceUrl: "https://github.com/modelcontextprotocol/inspector",
    triggerSignals: ["mcp_profile_changed"],
    allowedTools: ["tools/list"],
    readOnly: true,
  },
  "playwright-mcp": {
    id: "playwright-mcp",
    label: "Playwright MCP agentic browser check",
    command: "ut-tdd verify run --profile playwright-mcp",
    sourceType: "mcp",
    packageName: "@playwright/mcp",
    executable: "bun",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "bun add -D @playwright/mcp",
    sourceUrl: "https://github.com/microsoft/playwright-mcp",
    triggerSignals: ["ui_flow", "mcp_profile_changed"],
    allowedTools: ["browser_navigate", "browser_snapshot", "browser_click"],
    readOnly: false,
  },
  "docker-mcp-toolkit": {
    id: "docker-mcp-toolkit",
    label: "Docker MCP Toolkit isolated server profile",
    command: "ut-tdd mcp inspect docker-mcp-toolkit --method tools/list",
    sourceType: "mcp",
    packageName: "docker-mcp-toolkit",
    executable: "docker",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: true,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "high",
    installHint: "Install Docker MCP Toolkit through Docker Desktop after human approval.",
    sourceUrl: "https://docs.docker.com/ai/mcp-catalog-and-toolkit/toolkit/",
    triggerSignals: ["db_integration", "mcp_profile_changed"],
    optional: true,
    profileIsolation: "docker-desktop-mcp-toolkit",
    allowedTools: ["tools/list"],
    readOnly: false,
    requiresHumanApproval: true,
  },
  "vitest-browser-playwright": {
    id: "vitest-browser-playwright",
    label: "Vitest Browser Mode with Playwright provider",
    command: "bun run test -- --browser",
    sourceType: "test-foundation",
    packageName: "@vitest/browser-playwright",
    executable: "bun",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "low",
    installHint: "bun add -D @vitest/browser-playwright",
    sourceUrl: "https://vitest.dev/guide/browser/",
    triggerSignals: ["ui_flow"],
  },
  "github-mcp-readonly": {
    id: "github-mcp-readonly",
    label: "GitHub MCP read-only issue/PR/CI context",
    command: "ut-tdd verify run --profile github-mcp-readonly",
    sourceType: "mcp",
    packageName: "github-mcp-server",
    executable: null,
    authEnv: ["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_PERSONAL_ACCESS_TOKEN"],
    requiresNetwork: true,
    requiresDocker: false,
    requiresAuth: true,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "Install github/github-mcp-server and configure read-only toolsets.",
    sourceUrl: "https://github.com/github/github-mcp-server",
    triggerSignals: ["external_issue", "workflow_policy"],
    allowedTools: ["issues:read", "pull_requests:read", "actions:read"],
    readOnly: true,
    requiresHumanApproval: true,
  },
  testcontainers: {
    id: "testcontainers",
    label: "Testcontainers integration dependency check",
    command: "ut-tdd verify run --profile testcontainers",
    sourceType: "test-foundation",
    packageName: "testcontainers",
    executable: "docker",
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: true,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "medium",
    installHint: "bun add -D testcontainers",
    sourceUrl: "https://node.testcontainers.org/",
    triggerSignals: ["db_integration"],
  },
  msw: {
    id: "msw",
    label: "MSW API mock contract check",
    command: "ut-tdd verify run --profile msw",
    sourceType: "test-foundation",
    packageName: "msw",
    executable: null,
    authEnv: [],
    requiresNetwork: false,
    requiresDocker: false,
    requiresAuth: false,
    defaultEnabled: false,
    riskTier: "low",
    installHint: "bun add -D msw",
    sourceUrl: "https://mswjs.io/",
    triggerSignals: ["api_mock_gap"],
  },
};

// runner は固定 allowlist (ユーザー入力をコマンドへ連結しない)。readonly で実行時の動的追加を型で禁止し、
// 将来エントリを足すときは A-125 safety boundary (allow-list review) を経由する (A-128 F-4 / IMP-130(c))。
export const PROFILE_RUNNERS: Partial<
  Record<VerificationProfileId, readonly [string, readonly string[]]>
> = {
  "bun-unit": ["bun", ["run", "test"]] as const,
  doctor: ["bun", ["run", "src/cli.ts", "doctor"]] as const,
  "vitest-browser-playwright": ["bun", ["run", "test", "--", "--browser"]] as const,
};

export const SIGNAL_TO_PROFILE: Record<VerificationSignal, VerificationProfileId[]> = {
  source_change: ["bun-unit", "doctor"],
  ui_flow: ["vitest-browser-playwright", "playwright-mcp"],
  db_integration: ["testcontainers"],
  api_mock_gap: ["msw"],
  mcp_profile_changed: ["mcp-inspector-smoke"],
  external_issue: ["github-mcp-readonly"],
  workflow_policy: ["doctor"],
  doc_backprop: ["doctor"],
};
