import { type DocumentPack, doc } from "./proposal-document-pack-types";

export const DOCUMENT_PACKS_OPERATIONS: DocumentPack[] = [
  {
    pattern: "common-component",
    level: "G3",
    keywords: [
      "common component",
      "shared component",
      "library",
      "framework",
      "utility",
      "middleware",
      "\u5171\u901a\u90e8\u54c1",
      "\u5171\u901a\u30b3\u30f3\u30dd\u30fc\u30cd\u30f3\u30c8",
      "\u5171\u901a\u30e9\u30a4\u30d6\u30e9\u30ea",
    ],
    designDocs: [
      doc(
        "architecture",
        "docs/design/harness/L4-basic-design/architecture.md",
        "shared component architecture",
      ),
      doc("function", "docs/design/harness/L4-basic-design/function.md", "component contract"),
      doc(
        "module-decomposition",
        "docs/design/harness/L5-detailed-design/module-decomposition.md",
        "component boundary",
      ),
      doc(
        "function-spec",
        "docs/design/harness/L6-function-design/function-spec.md",
        "component function contract",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "component unit oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "component integration",
      ),
    ],
    evidence: [
      "component_api_contract",
      "reuse_impact",
      "compatibility_matrix",
      "dependency_impact",
    ],
    gates: ["common-component-review"],
  },
  {
    pattern: "security-privacy",
    level: "G4",
    keywords: [
      "authentication",
      "authorization",
      "permission",
      "role",
      "session",
      "token",
      "rbac",
      "mfa",
      "tenant",
      "pii",
      "privacy",
      "credential",
      "secret",
      "redaction",
      "\u8a8d\u8a3c",
      "\u8a8d\u53ef",
      "\u6a29\u9650",
      "\u30ed\u30fc\u30eb",
      "\u500b\u4eba\u60c5\u5831",
      "\u6a5f\u5bc6",
      "\u30c8\u30fc\u30af\u30f3",
      "\u30bb\u30c3\u30b7\u30e7\u30f3",
      "\u30c6\u30ca\u30f3\u30c8",
      "\u30de\u30b9\u30ad\u30f3\u30b0",
    ],
    designDocs: [
      doc("nfr", "docs/design/harness/L1-requirements/nfr.md", "security/privacy requirement"),
      doc(
        "technical-requirements",
        "docs/design/harness/L1-requirements/technical-requirements.md",
        "security/privacy technical boundary",
      ),
      doc(
        "architecture",
        "docs/design/harness/L4-basic-design/architecture.md",
        "security/privacy architecture",
      ),
      doc("data", "docs/design/harness/L4-basic-design/data.md", "privacy data boundary"),
      doc(
        "function-spec",
        "docs/design/harness/L6-function-design/function-spec.md",
        "security function contract",
      ),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "security acceptance",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "security/privacy system checks",
      ),
    ],
    evidence: [
      "role_permission_matrix",
      "privacy_data_classification",
      "abuse_cases",
      "negative_auth_tests",
      "human_security_approval",
    ],
    gates: ["security-privacy-review"],
  },
  {
    pattern: "error-observability-audit",
    level: "G4",
    keywords: [
      "error handling",
      "exception",
      "log",
      "audit log",
      "observability",
      "monitoring",
      "alert",
      "trace",
      "redaction",
      "incident",
      "on-call",
      "on call",
      "\u4f8b\u5916",
      "\u30a8\u30e9\u30fc",
      "\u30ed\u30b0",
      "\u76e3\u67fb\u30ed\u30b0",
      "\u76e3\u8996",
      "\u30a2\u30e9\u30fc\u30c8",
      "\u969c\u5bb3",
      "\u30a4\u30f3\u30b7\u30c7\u30f3\u30c8",
      "\u30aa\u30f3\u30b3\u30fc\u30eb",
    ],
    designDocs: [
      doc("nfr", "docs/design/harness/L1-requirements/nfr.md", "observability/audit requirement"),
      doc(
        "technical-requirements",
        "docs/design/harness/L1-requirements/technical-requirements.md",
        "observability technical boundary",
      ),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "error/audit processing",
      ),
      doc(
        "edge-case",
        "docs/design/harness/L6-function-design/edge-case.md",
        "exception and edge cases",
      ),
      doc(
        "review-evidence",
        "docs/design/harness/L6-function-design/review-evidence.md",
        "audit/review evidence",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "error/audit unit oracle",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "observability system behavior",
      ),
    ],
    evidence: [
      "error_taxonomy",
      "audit_log_schema",
      "alert_threshold",
      "redaction_policy",
      "failure_observability_tests",
    ],
    gates: ["error-observability-audit-review"],
  },
  {
    pattern: "ops-release-migration",
    level: "G4",
    keywords: [
      "release",
      "deployment",
      "rollback",
      "cutover",
      "migration",
      "operation",
      "runbook",
      "on-call",
      "on call",
      "incident",
      "\u30ea\u30ea\u30fc\u30b9",
      "\u30c7\u30d7\u30ed\u30a4",
      "\u5207\u66ff",
      "\u79fb\u884c",
      "\u904b\u7528",
      "\u30ed\u30fc\u30eb\u30d0\u30c3\u30af",
      "\u969c\u5bb3\u5bfe\u5fdc",
      "\u30aa\u30f3\u30b3\u30fc\u30eb",
    ],
    designDocs: [
      doc(
        "technical-requirements",
        "docs/design/harness/L1-requirements/technical-requirements.md",
        "release/operation requirement",
      ),
      doc("architecture", "docs/design/harness/L4-basic-design/architecture.md", "release impact"),
      doc("data", "docs/design/harness/L4-basic-design/data.md", "migration data impact"),
      doc(
        "physical-data",
        "docs/design/harness/L5-detailed-design/physical-data.md",
        "migration storage impact",
      ),
      doc(
        "handover-mechanism",
        "docs/design/harness/L6-function-design/handover-mechanism.md",
        "operation handover",
      ),
    ],
    testDocs: [
      doc(
        "operational-test-design",
        "docs/test-design/harness/L1-operational-test-design.md",
        "operation test plan",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "release/system verification",
      ),
    ],
    evidence: [
      "release_plan",
      "rollback_plan",
      "cutover_checklist",
      "migration_rehearsal",
      "operation_handover",
    ],
    gates: ["ops-release-migration-review"],
  },
  {
    pattern: "nfr-quality",
    level: "G4",
    keywords: [
      "nfr",
      "performance",
      "availability",
      "observability",
      "audit log",
      "security",
      "permission",
      "role",
      "pii",
      "\u975e\u6a5f\u80fd",
      "\u6027\u80fd",
      "\u53ef\u7528\u6027",
      "\u76e3\u67fb",
      "\u6a29\u9650",
      "\u30bb\u30ad\u30e5\u30ea\u30c6\u30a3",
    ],
    designDocs: [
      doc("nfr", "docs/design/harness/L1-requirements/nfr.md", "quality/security boundary"),
      doc(
        "technical-requirements",
        "docs/design/harness/L1-requirements/technical-requirements.md",
        "quality/security technical requirement",
      ),
      doc("nfr-grade", "docs/design/harness/L3-functional/nfr-grade.md", "quality grade"),
      doc(
        "architecture",
        "docs/design/harness/L4-basic-design/architecture.md",
        "quality/security architecture",
      ),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "quality acceptance",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "quality/security system check",
      ),
    ],
    evidence: ["nfr_grade", "security_or_performance_tests", "operations_review"],
    gates: ["nfr-quality-review"],
  },
  {
    pattern: "test-design",
    level: "G3",
    keywords: [
      "test plan",
      "test design",
      "test case",
      "test procedure",
      "test summary",
      "uat",
      "acceptance test",
      "regression test",
      "coverage",
      "\u30c6\u30b9\u30c8\u8a2d\u8a08",
      "\u30c6\u30b9\u30c8\u30b1\u30fc\u30b9",
      "\u53d7\u5165\u30c6\u30b9\u30c8",
      "\u56de\u5e30\u30c6\u30b9\u30c8",
    ],
    designDocs: [
      doc(
        "functional-requirements",
        "docs/design/harness/L3-functional/functional-requirements.md",
        "test objective source",
      ),
      doc(
        "function-spec",
        "docs/design/harness/L6-function-design/function-spec.md",
        "unit oracle source",
      ),
    ],
    testDocs: [
      doc(
        "operational-test-design",
        "docs/test-design/harness/L1-operational-test-design.md",
        "overall test strategy",
      ),
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "acceptance criteria and UAT",
      ),
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "unit test design",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "integration test design",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "system/regression test design",
      ),
    ],
    evidence: [
      "test_level_matrix",
      "oracle_matrix",
      "test_case_spec",
      "test_data",
      "entry_exit_criteria",
      "requirements_traceability",
    ],
    gates: ["test-design-coverage-review"],
  },
  {
    pattern: "backend-function",
    level: "G2",
    keywords: [
      "function",
      "service",
      "logic",
      "command",
      "cli",
      "\u6a5f\u80fd",
      "\u30b5\u30fc\u30d3\u30b9",
      "\u30ed\u30b8\u30c3\u30af",
    ],
    designDocs: [
      doc(
        "functional-requirements",
        "docs/design/harness/L3-functional/functional-requirements.md",
        "functional requirement",
      ),
      doc("function", "docs/design/harness/L4-basic-design/function.md", "basic function design"),
      doc(
        "function-spec",
        "docs/design/harness/L6-function-design/function-spec.md",
        "unit-level function contract",
      ),
    ],
    testDocs: [
      doc("unit-test-design", "docs/test-design/harness/L7-unit-test-design.md", "unit oracle"),
    ],
    evidence: ["oracle_ids", "targeted_unit_tests"],
    gates: ["pair-freeze"],
  },
  {
    pattern: "workflow-gate",
    level: "G3",
    keywords: [
      "gate",
      "plan lint",
      "plan routing",
      "plan gate",
      "ut-tdd plan",
      "doctor",
      "lint",
      "route",
      "classifier",
      "\u627f\u8a8d",
      "\u30b2\u30fc\u30c8",
    ],
    designDocs: [
      doc(
        "technical-requirements",
        "docs/design/harness/L1-requirements/technical-requirements.md",
        "workflow/tooling requirement",
      ),
      doc(
        "architecture",
        "docs/design/harness/L4-basic-design/architecture.md",
        "workflow architecture",
      ),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "workflow internals",
      ),
      doc(
        "function-spec",
        "docs/design/harness/L6-function-design/function-spec.md",
        "workflow contract",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "workflow unit oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "workflow integration",
      ),
    ],
    evidence: ["gate_contract", "regression_green", "doctor_or_lint_output"],
    gates: ["workflow-gate-review"],
  },
  {
    pattern: "agent-orchestration",
    level: "G3",
    keywords: ["agent", "provider", "delegation", "team run", "codex", "claude"],
    designDocs: [
      doc("agent-slots", "docs/design/harness/L6-function-design/agent-slots.md", "agent runtime"),
      doc(
        "cross-review-enforcement",
        "docs/design/harness/L6-function-design/cross-review-enforcement.md",
        "cross review",
      ),
      doc(
        "handover-mechanism",
        "docs/design/harness/L6-function-design/handover-mechanism.md",
        "handover",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "agent routing oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "agent integration",
      ),
    ],
    evidence: ["runtime_routing", "cross_review_evidence", "handover_evidence"],
    gates: ["agent-runtime-review"],
  },
  {
    pattern: "discovery",
    level: "G5",
    keywords: [
      "unknown",
      "uncertain",
      "poc",
      "hypothesis",
      "feasibility",
      "research",
      "\u4e0d\u660e",
      "\u4eee\u8aac",
      "\u8abf\u67fb",
      "\u5b9f\u73fe\u6027",
    ],
    designDocs: [
      doc(
        "roadmap-or-research",
        "docs/design/harness/L3-functional/roadmap.md",
        "uncertain design route",
      ),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "success condition",
      ),
    ],
    evidence: ["hypothesis", "poc_evidence", "s4_decision", "forward_or_reverse_route"],
    gates: ["discovery-s4-decision"],
  },
];
