import { type DocumentPack, doc } from "./proposal-document-pack-types";

export const DOCUMENT_PACKS_CORE: DocumentPack[] = [
  {
    pattern: "screen-ui",
    level: "G3",
    keywords: [
      "screen",
      "ui",
      "view",
      "form",
      "navigation",
      "\u753b\u9762",
      "\u753b\u9762\u8a2d\u8a08",
      "\u753b\u9762\u4e00\u89a7",
      "\u30d5\u30a9\u30fc\u30e0",
    ],
    designDocs: [
      doc(
        "screen-requirements",
        "docs/design/harness/L1-requirements/screen-requirements.md",
        "screen proposal",
      ),
      doc("screen-list", "docs/design/harness/L2-screen/screen-list.md", "screen inventory"),
      doc("screen-flow", "docs/design/harness/L2-screen/screen-flow.md", "screen transition flow"),
      doc(
        "screen-detail",
        "docs/design/harness/L2-screen/screen-detail.md",
        "screen behavior/detail",
      ),
      doc("wireframe", "docs/design/harness/L2-screen/wireframe.md", "layout expectation"),
      doc("ui-element", "docs/design/harness/L2-screen/ui-element.md", "UI element contract"),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "user-visible screen behavior",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "screen integration path",
      ),
    ],
    evidence: ["screen_trace", "wireframe_or_mock", "ui_component_trace"],
    gates: ["screen-design-workflow"],
  },
  {
    pattern: "business-flow",
    level: "G3",
    keywords: [
      "business flow",
      "workflow",
      "\u696d\u52d9",
      "\u696d\u52d9\u30d5\u30ed\u30fc",
      "\u30d5\u30ed\u30fc",
    ],
    designDocs: [
      doc(
        "business-requirements",
        "docs/design/harness/L1-requirements/business-requirements.md",
        "business flow",
      ),
      doc(
        "business-flow",
        "docs/design/harness/L2-screen/business-flow.md",
        "business operation flow",
      ),
      doc(
        "business-detail",
        "docs/design/harness/L3-functional/business-detail.md",
        "business rule detail",
      ),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "business acceptance",
      ),
    ],
    evidence: ["business_rule_trace", "acceptance_criteria"],
    gates: ["business-flow-review"],
  },
  {
    pattern: "frontend-design",
    level: "G3",
    keywords: ["frontend", "visual", "token", "a11y", "accessibility", "vrt", "ux"],
    designDocs: [
      doc("nfr", "docs/design/harness/L1-requirements/nfr.md", "frontend quality requirement"),
      doc("nfr-grade", "docs/design/harness/L3-functional/nfr-grade.md", "quality grade"),
      doc("screen-detail", "docs/design/harness/L2-screen/screen-detail.md", "frontend behavior"),
      doc("ui-element", "docs/design/harness/L2-screen/ui-element.md", "frontend components"),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "UX acceptance",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "visual/system checks",
      ),
    ],
    evidence: ["tokens", "a11y", "vrt", "ux_review"],
    gates: ["frontend-design-workflow"],
  },
  {
    pattern: "ux-research-usability",
    level: "G3",
    keywords: [
      "ux research",
      "usability",
      "journey map",
      "user journey",
      "persona",
      "prototype",
      "card sorting",
      "moderated test",
      "figma",
      "miro",
      "\u30e6\u30fc\u30b6\u30d3\u30ea\u30c6\u30a3",
      "\u30e6\u30fc\u30b6\u30fc\u30b8\u30e3\u30fc\u30cb\u30fc",
      "\u30da\u30eb\u30bd\u30ca",
      "\u30d7\u30ed\u30c8\u30bf\u30a4\u30d7",
    ],
    designDocs: [
      doc(
        "screen-requirements",
        "docs/design/harness/L1-requirements/screen-requirements.md",
        "UX research target",
      ),
      doc("business-flow", "docs/design/harness/L2-screen/business-flow.md", "user journey flow"),
      doc("screen-flow", "docs/design/harness/L2-screen/screen-flow.md", "user task flow"),
      doc("screen-detail", "docs/design/harness/L2-screen/screen-detail.md", "usability scenario"),
      doc("wireframe", "docs/design/harness/L2-screen/wireframe.md", "prototype/wireframe"),
      doc("nfr-grade", "docs/design/harness/L3-functional/nfr-grade.md", "usability quality grade"),
    ],
    testDocs: [
      doc(
        "acceptance-test-design",
        "docs/test-design/harness/L3-acceptance-test-design.md",
        "UX acceptance task",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "usability/system validation",
      ),
    ],
    evidence: [
      "user_journey_map",
      "usability_test_plan",
      "task_scenarios",
      "participant_criteria",
      "ux_findings_trace",
    ],
    gates: ["ux-research-review"],
  },
  {
    pattern: "api-if",
    level: "G3",
    keywords: [
      "api",
      "external api",
      "webhook",
      "interface",
      "adapter",
      "\u5916\u90e8\u9023\u643a",
      "\u30a4\u30f3\u30bf\u30fc\u30d5\u30a7\u30fc\u30b9",
    ],
    designDocs: [
      doc(
        "external-if",
        "docs/design/harness/L4-basic-design/external-if.md",
        "external/interface contract",
      ),
      doc("if-detail", "docs/design/harness/L5-detailed-design/if-detail.md", "interface detail"),
    ],
    testDocs: [
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "contract/integration path",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "external behavior",
      ),
    ],
    evidence: ["contract_tests", "failure_cases", "timeout_cases"],
    gates: ["if-contract-review"],
  },
  {
    pattern: "data-db",
    level: "G3",
    keywords: [
      "db",
      "database",
      "schema",
      "migration",
      "storage",
      "projection",
      "\u30c7\u30fc\u30bf",
      "\u30b9\u30ad\u30fc\u30de",
      "\u79fb\u884c",
    ],
    designDocs: [
      doc("data", "docs/design/harness/L4-basic-design/data.md", "data model"),
      doc(
        "physical-data",
        "docs/design/harness/L5-detailed-design/physical-data.md",
        "physical data design",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "data unit oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "migration/data integration",
      ),
    ],
    evidence: ["migration_plan", "rollback_plan", "data_integrity_tests"],
    gates: ["data-contract-review"],
  },
  {
    pattern: "batch-report",
    level: "G3",
    keywords: [
      "batch",
      "job",
      "cron",
      "scheduled",
      "import",
      "export",
      "report",
      "csv",
      "\u30d0\u30c3\u30c1",
      "\u5e33\u7968",
      "\u53d6\u8fbc",
      "\u51fa\u529b",
    ],
    designDocs: [
      doc(
        "functional-requirements",
        "docs/design/harness/L3-functional/functional-requirements.md",
        "batch/report function",
      ),
      doc("function", "docs/design/harness/L4-basic-design/function.md", "batch/report behavior"),
      doc("data", "docs/design/harness/L4-basic-design/data.md", "batch/report data flow"),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "batch/report internal processing",
      ),
      doc(
        "physical-data",
        "docs/design/harness/L5-detailed-design/physical-data.md",
        "batch/report storage boundary",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "batch/report unit oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "batch/report integration",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "batch/report operational behavior",
      ),
    ],
    evidence: ["schedule_or_trigger", "idempotency", "retry_policy", "data_volume_case"],
    gates: ["batch-report-review"],
  },
  {
    pattern: "report-output",
    level: "G3",
    keywords: [
      "report output",
      "pdf",
      "excel",
      "xlsx",
      "\u5e33\u7968",
      "\u5e33\u7968\u8a2d\u8a08",
      "\u51fa\u529b",
      "\u5370\u5237",
      "\u96c6\u8a08",
      "\u6587\u5b57\u30b3\u30fc\u30c9",
    ],
    designDocs: [
      doc(
        "functional-requirements",
        "docs/design/harness/L3-functional/functional-requirements.md",
        "report/output requirement",
      ),
      doc("function", "docs/design/harness/L4-basic-design/function.md", "report/output behavior"),
      doc("data", "docs/design/harness/L4-basic-design/data.md", "report/output data source"),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "report/output generation flow",
      ),
      doc(
        "physical-data",
        "docs/design/harness/L5-detailed-design/physical-data.md",
        "report/output data format",
      ),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "report/output unit oracle",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "report/output validation",
      ),
    ],
    evidence: [
      "output_layout",
      "sort_and_grouping_rules",
      "format_encoding",
      "sample_output",
      "large_volume_case",
    ],
    gates: ["report-output-review"],
  },
  {
    pattern: "async-job-flow",
    level: "G3",
    keywords: [
      "async",
      "asynchronous",
      "queue",
      "message queue",
      "event",
      "delayed",
      "job flow",
      "\u975e\u540c\u671f",
      "\u30ad\u30e5\u30fc",
      "\u30e1\u30c3\u30bb\u30fc\u30b8\u30f3\u30b0",
      "\u30b8\u30e7\u30d6\u30d5\u30ed\u30fc",
    ],
    designDocs: [
      doc(
        "architecture",
        "docs/design/harness/L4-basic-design/architecture.md",
        "async/job architecture",
      ),
      doc("function", "docs/design/harness/L4-basic-design/function.md", "async/job behavior"),
      doc("external-if", "docs/design/harness/L4-basic-design/external-if.md", "async boundary"),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "async/job processing",
      ),
      doc("if-detail", "docs/design/harness/L5-detailed-design/if-detail.md", "message contract"),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "async unit oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "async integration",
      ),
      doc(
        "system-test-design",
        "docs/test-design/harness/L9-system-test-design.md",
        "async operational behavior",
      ),
    ],
    evidence: [
      "job_flow",
      "message_contract",
      "retry_dead_letter_policy",
      "ordering_idempotency",
      "replay_recovery_case",
    ],
    gates: ["async-job-flow-review"],
  },
  {
    pattern: "notification-message",
    level: "G3",
    keywords: [
      "email",
      "mail",
      "notification",
      "message",
      "template",
      "sms",
      "slack",
      "\u30e1\u30fc\u30eb",
      "\u901a\u77e5",
      "\u30e1\u30c3\u30bb\u30fc\u30b8",
    ],
    designDocs: [
      doc(
        "functional-requirements",
        "docs/design/harness/L3-functional/functional-requirements.md",
        "notification requirement",
      ),
      doc(
        "external-if",
        "docs/design/harness/L4-basic-design/external-if.md",
        "notification channel",
      ),
      doc(
        "internal-processing",
        "docs/design/harness/L5-detailed-design/internal-processing.md",
        "notification processing",
      ),
      doc("if-detail", "docs/design/harness/L5-detailed-design/if-detail.md", "message payload"),
      doc("nfr", "docs/design/harness/L1-requirements/nfr.md", "notification privacy/availability"),
    ],
    testDocs: [
      doc(
        "unit-test-design",
        "docs/test-design/harness/L7-unit-test-design.md",
        "message rendering oracle",
      ),
      doc(
        "integration-test-design",
        "docs/test-design/harness/L8-integration-test-design.md",
        "notification integration",
      ),
    ],
    evidence: [
      "recipient_rules",
      "message_template",
      "delivery_failure_case",
      "locale_timezone_case",
      "privacy_redaction_case",
    ],
    gates: ["notification-message-review"],
  },
];
