import { join } from "node:path";
import type { GeneratedFile } from "./index";

export type TemplateSet = { [name: string]: string };

const CLAUDE_AGENT_TEMPLATES = [
  ["be-api", "Backend API reviewer for route, contract, and integration concerns."],
  ["be-logic", "Backend domain logic reviewer for invariants, boundaries, and TDD fit."],
  [
    "code-reviewer",
    "Read-only senior engineering reviewer for correctness, security, and maintainability.",
  ],
  ["db-schema", "Database schema reviewer for migrations, indexes, and data contracts."],
  ["devops-deploy", "CI, deployment, rollback, and release-readiness reviewer."],
  [
    "pdm-innovation-manager",
    "Product management reviewer for opportunity, scope, and portfolio fit.",
  ],
  ["pdm-marketing-innovation", "Market and user-value reviewer for product framing and adoption."],
  [
    "pdm-tech-innovation",
    "Technical product reviewer for feasibility, platform leverage, and risk.",
  ],
  ["pmo-haiku", "Lightweight PMO reviewer for concise status, blockers, and next action."],
  ["pmo-project-explorer", "Project discovery reviewer for goals, constraints, and evidence gaps."],
  ["pmo-project-scout", "Project triage reviewer for backlog, ownership, and workflow routing."],
  [
    "pmo-sonnet",
    "PMO reviewer for plan structure, handover quality, and cross-document consistency.",
  ],
  ["pmo-tech-docs", "Technical documentation reviewer for ADR, process, and governance quality."],
  ["pmo-tech-fork", "Fork, extraction, and distribution reviewer for clean-room boundaries."],
  ["pmo-tech-news", "Technical research reviewer for external signals and dated source checks."],
  ["qa-test", "Quality reviewer for test strategy, oracle strength, and regression scope."],
  [
    "refactor-scout",
    "Refactoring reviewer for complexity, duplication, and low-risk extraction candidates.",
  ],
  ["security-audit", "Security reviewer for auth, secrets, PII, and threat-model concerns."],
  [
    "ut-tdd-tl",
    "Technical-lead reviewer for UT-TDD workflow, gates, tests, and release readiness.",
  ],
] as const;

const CLAUDE_COMMAND_TEMPLATES = [
  ["build", "Implement against a frozen UT-TDD spec/test design."],
  ["code-simplify", "Identify the smallest safe simplification for the selected code."],
  ["sdd-plan", "Create a spec-driven UT-TDD plan before implementation."],
  ["sdd-review", "Review a spec/design against UT-TDD trace and gate requirements."],
  ["ship", "Prepare release evidence, rollback notes, and final verification."],
  ["spec", "Author a spec-first design before any implementation."],
  ["test", "Run targeted UT-TDD verification for the current change."],
] as const;

function agentTemplate(name: string, description: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "tools: Read, Grep, Glob, Bash",
    "---",
    "",
    "Act as a consumer-safe UT-TDD subagent for the current repository.",
    "",
    "Required baseline:",
    "- Read `AGENTS.md`, `CLAUDE.md`, and `.claude/CLAUDE.md` when present.",
    "- Use `ut-tdd status` and `ut-tdd doctor` as local state evidence.",
    "- Report findings before summaries, with file and command evidence.",
    "- Do not write secrets, credentials, PII, or machine-local absolute paths.",
    "- Prefer read-only review unless the user explicitly asks for implementation.",
    "",
  ].join("\n");
}

function commandTemplate(name: string, description: string): string {
  return [
    "---",
    `description: ${description}`,
    'argument-hint: "<target>"',
    "---",
    "",
    `Command: ${name}`,
    "",
    "Target: $ARGUMENTS",
    "",
    "Use repository-local UT-TDD commands. Start with `ut-tdd status --json`, run the narrow verification for the target, and finish with `ut-tdd doctor` when workflow or gate behavior is affected.",
    "",
  ].join("\n");
}

const CLAUDE_AGENT_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_AGENT_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/agents/${name}.md`,
    agentTemplate(name, description),
  ]),
);

const CLAUDE_COMMAND_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_COMMAND_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/commands/${name}.md`,
    commandTemplate(name, description),
  ]),
);

const CLAUDE_AGENT_FILES: { template: string; file: GeneratedFile }[] = CLAUDE_AGENT_TEMPLATES.map(
  ([name]) => ({
    template: `adapter/.claude/agents/${name}.md`,
    file: {
      path: join(".claude", "agents", `${name}.md`),
      category: "A",
      purpose: `Claude subagent template: ${name}`,
    },
  }),
);

const CLAUDE_COMMAND_FILES: { template: string; file: GeneratedFile }[] =
  CLAUDE_COMMAND_TEMPLATES.map(([name]) => ({
    template: `adapter/.claude/commands/${name}.md`,
    file: {
      path: join(".claude", "commands", `${name}.md`),
      category: "A",
      purpose: `Claude slash command template: ${name}`,
    },
  }));

export const BUILTIN_GITHUB_TEMPLATES: TemplateSet = {
  ...CLAUDE_AGENT_TEMPLATE_SET,
  ...CLAUDE_COMMAND_TEMPLATE_SET,
  "common/ut-tdd.mjs": [
    "#!/usr/bin/env bun",
    'import { existsSync } from "node:fs";',
    'import { join } from "node:path";',
    'import { spawnSync } from "node:child_process";',
    "",
    "const repoRoot = process.cwd();",
    'const localBin = join(repoRoot, "node_modules", ".bin", process.platform === "win32" ? "ut-tdd.cmd" : "ut-tdd");',
    "const setupSourceCli = {{UT_TDD_SOURCE_CLI_JSON}};",
    'const command = existsSync(setupSourceCli) ? "bun" : existsSync(localBin) ? localBin : "ut-tdd";',
    'const args = command === "bun" ? [setupSourceCli, ...process.argv.slice(2)] : process.argv.slice(2);',
    "const result = spawnSync(command, args, {",
    '  stdio: "inherit",',
    '  shell: process.platform === "win32",',
    "});",
    "",
    "if (result.error) {",
    '  console.error("[ut-tdd-wrapper] Failed to launch project-local ut-tdd.");',
    '  console.error("[ut-tdd-wrapper] Add UT-TDD as a project dependency, keep the setup harness checkout available, or verify `ut-tdd --help` in this repository shell.");',
    "  console.error(result.error.message);",
    "  process.exit(127);",
    "}",
    "",
    "process.exit(result.status ?? 0);",
    "",
  ].join("\n"),
  "adapter/AGENTS.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Adapter",
    "",
    "This project uses UT-TDD Agent Harness commands as the local orchestration surface.",
    "",
    "- Status: `ut-tdd status`",
    "- Doctor: `ut-tdd doctor`",
    "- Handover: `ut-tdd handover`",
    '- Codex delegation: `ut-tdd codex --role <role> --task "..."`',
    '- Claude delegation: `ut-tdd claude --role <role> --task "..."`',
    "- Team run: `ut-tdd team run --definition .ut-tdd/teams/<team>.yaml`",
    "",
    "Project-owned instructions outside this managed block remain consumer-owned.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Shared Context",
    "",
    "Use repository-local UT-TDD commands for harness state and delegation.",
    "",
    "- `ut-tdd status` reports the local runtime mode.",
    "- `ut-tdd doctor` runs repository health checks.",
    "- `ut-tdd handover` reads and writes cross-runtime handover state.",
    '- `ut-tdd codex --role <role> --task "..."` delegates to Codex.',
    '- `ut-tdd claude --role <role> --task "..."` delegates to Claude.',
    "",
    "Do not put secrets, tokens, or machine-local absolute paths in adapter docs.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# Claude Runtime Adapter",
    "",
    "Claude Code sessions should route harness lifecycle work through `ut-tdd`.",
    "Consumer-owned Claude instructions can be added outside this managed block.",
    "",
    "- Session evidence: `ut-tdd status` and `ut-tdd handover`",
    "- Health check: `ut-tdd doctor`",
    "- Review separation: use another runtime/model family when feasible",
    "",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/settings.json": [
    "{",
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "Agent|Task",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "Edit|Write|MultiEdit",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Edit|Write|MultiEdit|Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "    ,",
    '    "SubagentStop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook subagent-stop",',
    '            "timeout": 5,',
    '            "statusMessage": "agent-slots: release oldest guard slot (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.codex/config.toml": ["[features]", "hooks = true", ""].join("\n"),
  "adapter/.codex/hooks.json": [
    "{",
    '  "$comment": "UT-TDD Codex adapter hooks. Hosted/API tool surfaces still require explicit `ut-tdd guard preflight` before edits because repo-local Codex hooks do not execute there.",',
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "spawn_agent|spawn_agents_on_csv",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook agent-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: Codex subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "apply_patch|write_file",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook work-guard",',
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs session start",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "apply_patch|write_file|exec_command|local_shell",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs hook post-tool-use",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    '            "command": "bun .ut-tdd/bin/ut-tdd.mjs session summary",',
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.claude/commands/ut-tdd-status.md": [
    "---",
    "description: Show UT-TDD status and doctor output",
    "---",
    "",
    "Run `ut-tdd status --json` and `ut-tdd doctor`, then summarize mode, active drafts, open defers, and hard-gate failures.",
    "",
  ].join("\n"),
  "adapter/.claude/commands/ut-tdd-test.md": [
    "---",
    "description: Run UT-TDD verification for the current change",
    'argument-hint: "<changed area or PLAN id>"',
    "---",
    "",
    "Target: $ARGUMENTS",
    "",
    "Run the narrow Vitest target first, then `bun run typecheck`, `bun run lint`, and `ut-tdd doctor` when the change affects core workflow or gates.",
    "",
  ].join("\n"),
  "common/harness-check.yml": [
    "name: harness-check",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "jobs:",
    "  harness-check:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - run: bun run typecheck",
    "      - run: bun run test",
    "",
  ].join("\n"),
  "common/commitlint.config.js":
    "module.exports = { extends: ['@commitlint/config-conventional'] };\n",
  "common/escalation-stale.yml": [
    "name: escalation-stale",
    "on:",
    "  schedule:",
    "    - cron: '0 0 * * 1'",
    "jobs:",
    "  noop:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - run: echo escalation policy placeholder",
    "",
  ].join("\n"),
  "common/recovery.md":
    "# Recovery\n\nDescribe the broken invariant, evidence, and rollback path.\n",
  "common/add-feature.md":
    "# Add Feature\n\nDescribe objective, scope, tests, and review evidence.\n",
  "common/PULL_REQUEST_TEMPLATE.md":
    "## Summary\n\n## Verification\n\n## Review evidence\n\nCloses #\n",
  "team/CODEOWNERS": [
    "* {{TL_TEAM}}",
    "/docs/ {{PO_TEAM}}",
    "/src/ {{TL_TEAM}}",
    "/tests/ {{QA_TEAM}}",
    "",
  ].join("\n"),
  "team/setup-branch-protection.sh": [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'REPO="$' + '{1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"',
    'echo "Apply branch protection to $' + '{REPO}/main"',
    'read -r -p "Continue? [y/N] " ans',
    '[[ "$' + '{ans}" == "y" || "$' + '{ans}" == "Y" ]] || exit 1',
    'gh api -X PUT "repos/$' + '{REPO}/branches/main/protection" \\',
    '  -H "Accept: application/vnd.github+json" \\',
    "  --input - <<'JSON'",
    "{",
    '  "required_status_checks": { "strict": true, "checks": [ { "context": "harness-check" } ] },',
    '  "enforce_admins": true,',
    '  "required_pull_request_reviews": { "required_approving_review_count": 1 },',
    '  "restrictions": null',
    "}",
    "JSON",
    "",
  ].join("\n"),
};

export const COMMON_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "common/ut-tdd.mjs",
    file: {
      path: join(".ut-tdd", "bin", "ut-tdd.mjs"),
      category: "A",
      purpose: "Project-local UT-TDD hook wrapper",
    },
  },
  {
    template: "adapter/AGENTS.md",
    file: {
      path: "AGENTS.md",
      category: "A",
      purpose: "UT-TDD adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/CLAUDE.md",
    file: {
      path: "CLAUDE.md",
      category: "A",
      purpose: "UT-TDD shared adapter context (managed block)",
    },
  },
  {
    template: "adapter/.codex/config.toml",
    file: {
      path: join(".codex", "config.toml"),
      category: "A",
      purpose: "Codex project-local hook enablement",
    },
  },
  {
    template: "adapter/.codex/hooks.json",
    file: {
      path: join(".codex", "hooks.json"),
      category: "A",
      purpose: "Codex hook settings for UT-TDD CLI entrypoints",
    },
  },
  {
    template: "adapter/.claude/CLAUDE.md",
    file: {
      path: join(".claude", "CLAUDE.md"),
      category: "A",
      purpose: "Claude runtime adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/.claude/settings.json",
    file: {
      path: join(".claude", "settings.json"),
      category: "A",
      purpose: "Claude hook settings for UT-TDD CLI entrypoints",
    },
  },
  ...CLAUDE_AGENT_FILES,
  ...CLAUDE_COMMAND_FILES,
  {
    template: "adapter/.claude/commands/ut-tdd-status.md",
    file: {
      path: join(".claude", "commands", "ut-tdd-status.md"),
      category: "A",
      purpose: "Claude slash command for UT-TDD status checks",
    },
  },
  {
    template: "adapter/.claude/commands/ut-tdd-test.md",
    file: {
      path: join(".claude", "commands", "ut-tdd-test.md"),
      category: "A",
      purpose: "Claude slash command for UT-TDD verification",
    },
  },
  {
    template: "common/harness-check.yml",
    file: {
      path: join(".github", "workflows", "harness-check.yml"),
      category: "A",
      purpose: "CI (typecheck + regression)",
    },
  },
  {
    template: "common/commitlint.config.js",
    file: { path: "commitlint.config.js", category: "A", purpose: "Conventional Commits" },
  },
  {
    template: "common/escalation-stale.yml",
    file: {
      path: join(".github", "workflows", "escalation-stale.yml"),
      category: "A",
      purpose: "stale escalation issue workflow",
    },
  },
  {
    template: "common/recovery.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "recovery.md"),
      category: "A",
      purpose: "Recovery issue template",
    },
  },
  {
    template: "common/add-feature.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "add-feature.md"),
      category: "A",
      purpose: "Add-feature issue template",
    },
  },
  {
    template: "common/PULL_REQUEST_TEMPLATE.md",
    file: {
      path: join(".github", "PULL_REQUEST_TEMPLATE.md"),
      category: "A",
      purpose: "PR template",
    },
  },
];
