import { join } from "node:path";
// Hook 配線の単一定義源: 生成 settings.json / hooks.json の command は project-hook lint の
// wrapper 正規形から構築する (gate 要求と setup 生成物の再乖離防止、PLAN-RECOVERY-06)。
import { wrapperHookCommand } from "../lint/project-hook";
// model ID は SSoT (src/team/model-policy.ts MODEL_IDS) 参照のみ。生 literal の二重保持は
// 世代 drift の温床 (A-177 F-5 / PLAN-L7-256: templates が opus-4-7 のまま SSoT と乖離した実績)。
import { MODEL_IDS } from "../team/model-policy";
import type { GeneratedFile } from "./index";

export type TemplateSet = { [name: string]: string };

const CLAUDE_OPUS = MODEL_IDS.claude.opus;
const CLAUDE_SONNET = MODEL_IDS.claude.sonnet;
const CLAUDE_HAIKU = MODEL_IDS.claude.haiku;
const GPT_FRONTIER = MODEL_IDS.codex.frontier;
const GPT_WORKER = MODEL_IDS.codex.worker;
const GPT_SPARK = MODEL_IDS.codex.spark;

const CLAUDE_AGENT_TEMPLATES = [
  ["be-api", "Backend API reviewer for route, contract, and integration concerns.", CLAUDE_SONNET],
  [
    "be-logic",
    "Backend domain logic reviewer for invariants, boundaries, and TDD fit.",
    CLAUDE_SONNET,
  ],
  [
    "code-reviewer",
    "Read-only senior engineering reviewer for correctness, security, and maintainability.",
    CLAUDE_SONNET,
  ],
  [
    "db-schema",
    "Database schema reviewer for migrations, indexes, and data contracts.",
    CLAUDE_SONNET,
  ],
  ["devops-deploy", "CI, deployment, rollback, and release-readiness reviewer.", CLAUDE_SONNET],
  [
    "pdm-innovation-manager",
    "Product management reviewer for opportunity, scope, and portfolio fit.",
    CLAUDE_OPUS,
  ],
  [
    "pdm-marketing-innovation",
    "Market and user-value reviewer for product framing and adoption.",
    CLAUDE_OPUS,
  ],
  [
    "pdm-tech-innovation",
    "Technical product reviewer for feasibility, platform leverage, and risk.",
    CLAUDE_OPUS,
  ],
  [
    "pmo-haiku",
    "Lightweight PMO reviewer for concise status, blockers, and next action.",
    CLAUDE_HAIKU,
  ],
  [
    "pmo-project-explorer",
    "Project discovery reviewer for goals, constraints, and evidence gaps.",
    CLAUDE_SONNET,
  ],
  [
    "pmo-project-scout",
    "Project triage reviewer for backlog, ownership, and workflow routing.",
    CLAUDE_HAIKU,
  ],
  [
    "pmo-sonnet",
    "PMO reviewer for plan structure, handover quality, and cross-document consistency.",
    CLAUDE_SONNET,
  ],
  [
    "pmo-tech-docs",
    "Technical documentation reviewer for ADR, process, and governance quality.",
    CLAUDE_SONNET,
  ],
  [
    "pmo-tech-fork",
    "Fork, extraction, and distribution reviewer for clean-room boundaries.",
    CLAUDE_SONNET,
  ],
  [
    "pmo-tech-news",
    "Technical research reviewer for external signals and dated source checks.",
    CLAUDE_SONNET,
  ],
  [
    "qa-test",
    "Quality reviewer for test strategy, oracle strength, and regression scope.",
    CLAUDE_SONNET,
  ],
  [
    "refactor-scout",
    "Refactoring reviewer for complexity, duplication, and low-risk extraction candidates.",
    CLAUDE_HAIKU,
  ],
  [
    "security-audit",
    "Security reviewer for auth, secrets, PII, and threat-model concerns.",
    CLAUDE_SONNET,
  ],
  [
    "ut-tdd-tl",
    "Technical-lead reviewer for UT-TDD workflow, gates, tests, and release readiness.",
    CLAUDE_SONNET,
  ],
] as const;

const CLAUDE_COMMAND_TEMPLATES = [
  ["build", "Implement against a frozen UT-TDD spec/test design."],
  ["code-simplify", "Identify the smallest safe simplification for the selected code."],
  ["sdd-plan", "Create a spec-driven UT-TDD plan before implementation."],
  ["sdd-review", "Review a spec/design against UT-TDD trace and gate requirements."],
  ["ship", "Prepare release evidence, rollback notes, and final verification."],
  ["spec", "Author a spec-first design before any implementation."],
  ["test", "Run targeted UT-TDD verification for the current change."],
] as const;

function agentTemplate(name: string, description: string, model: string): string {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "tools: Read, Grep, Glob, Bash",
    `model: ${model}`,
    "---",
    "",
    "Act as a consumer-safe UT-TDD subagent for the current repository.",
    "",
    "Required baseline:",
    "- Read `AGENTS.md`, `CLAUDE.md`, and `.claude/CLAUDE.md` when present.",
    "- Use `ut-tdd status`, `ut-tdd doctor --profile consumer-setup-smoke`, and `ut-tdd doctor --profile consumer-toolchain` as consumer-safe local state evidence.",
    "- Report findings before summaries, with file and command evidence.",
    "- Do not write secrets, credentials, PII, or machine-local absolute paths.",
    "- Prefer read-only review unless the user explicitly asks for implementation.",
    "",
  ].join("\n");
}

function commandTemplate(name: string, description: string): string {
  return [
    "---",
    `description: ${description}`,
    'argument-hint: "<target>"',
    "---",
    "",
    `Command: ${name}`,
    "",
    "Target: $ARGUMENTS",
    "",
    "Use repository-local UT-TDD commands. Start with `ut-tdd status --json`, run the narrow verification for the target, use `ut-tdd doctor --profile consumer-setup-smoke` for generated adapter/setup health, and use `ut-tdd doctor --profile consumer-toolchain` for consumer-safe toolchain health. Full `ut-tdd doctor` is for source/governance repositories with PLAN/design/test-design artifacts.",
    "",
  ].join("\n");
}

const CLAUDE_AGENT_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_AGENT_TEMPLATES.map(([name, description, model]) => [
    `adapter/.claude/agents/${name}.md`,
    agentTemplate(name, description, model),
  ]),
);

const CLAUDE_COMMAND_TEMPLATE_SET: TemplateSet = Object.fromEntries(
  CLAUDE_COMMAND_TEMPLATES.map(([name, description]) => [
    `adapter/.claude/commands/${name}.md`,
    commandTemplate(name, description),
  ]),
);

const CLAUDE_AGENT_FILES: { template: string; file: GeneratedFile }[] = CLAUDE_AGENT_TEMPLATES.map(
  ([name]) => ({
    template: `adapter/.claude/agents/${name}.md`,
    file: {
      path: join(".claude", "agents", `${name}.md`),
      category: "A",
      purpose: `Claude subagent template: ${name}`,
    },
  }),
);

const CLAUDE_COMMAND_FILES: { template: string; file: GeneratedFile }[] =
  CLAUDE_COMMAND_TEMPLATES.map(([name]) => ({
    template: `adapter/.claude/commands/${name}.md`,
    file: {
      path: join(".claude", "commands", `${name}.md`),
      category: "A",
      purpose: `Claude slash command template: ${name}`,
    },
  }));

export const BUILTIN_GITHUB_TEMPLATES: TemplateSet = {
  ...CLAUDE_AGENT_TEMPLATE_SET,
  ...CLAUDE_COMMAND_TEMPLATE_SET,
  "common/ut-tdd.mjs": [
    "#!/usr/bin/env bun",
    'import { existsSync } from "node:fs";',
    'import { join } from "node:path";',
    'import { spawnSync } from "node:child_process";',
    "",
    "const repoRoot = process.cwd();",
    'const localBin = join(repoRoot, "node_modules", ".bin", process.platform === "win32" ? "ut-tdd.cmd" : "ut-tdd");',
    "// Repo-local harness source (Pack checkout topology). Resolved relative to cwd so the",
    "// wrapper keeps working on CI runners where the setup machine's absolute path does not",
    "// exist (A-172 C-2). Both files are required so an unrelated consumer src/cli.ts is not",
    "// misresolved as the harness CLI.",
    'const repoLocalCli = join(repoRoot, "src", "cli.ts");',
    'const repoLocalHarness = existsSync(repoLocalCli) && existsSync(join(repoRoot, "src", "setup", "index.ts"));',
    "const setupSourceCli = {{UT_TDD_SOURCE_CLI_JSON}};",
    "const sourceCli = repoLocalHarness ? repoLocalCli : setupSourceCli;",
    'const command = existsSync(localBin) ? localBin : existsSync(sourceCli) ? "bun" : "ut-tdd";',
    'const args = command === "bun" ? [sourceCli, ...process.argv.slice(2)] : process.argv.slice(2);',
    "const result = spawnSync(command, args, {",
    '  stdio: "inherit",',
    '  shell: process.platform === "win32",',
    "});",
    "",
    "if (result.error) {",
    '  console.error("[ut-tdd-wrapper] Failed to launch project-local ut-tdd.");',
    '  console.error("[ut-tdd-wrapper] Add UT-TDD as a project dependency, keep the setup Pack checkout available, or verify `ut-tdd --help` in this repository shell.");',
    "  console.error(result.error.message);",
    "  process.exit(127);",
    "}",
    "",
    "process.exit(result.status ?? 0);",
    "",
  ].join("\n"),
  "adapter/AGENTS.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Adapter",
    "",
    "This project uses UT-TDD Agent Harness commands as the local orchestration surface.",
    "",
    "- Status: `ut-tdd status`",
    "- Setup doctor: `ut-tdd doctor --profile consumer-setup-smoke`",
    "- Toolchain doctor: `ut-tdd doctor --profile consumer-toolchain`",
    "- Full doctor: `ut-tdd doctor` (source/governance repositories only)",
    "- Handover: `ut-tdd handover`",
    '- Codex delegation: `ut-tdd codex --role <role> --task "..."`',
    '- Claude delegation: `ut-tdd claude --role <role> --task "..."`',
    "- Team run: `ut-tdd team run --definition .ut-tdd/teams/<team>.yaml`",
    "",
    "## GPT / Codex runtime defaults",
    "",
    `- Implementation lanes default to worker-class models (\`${GPT_WORKER}\`); lightweight parallel lanes use spark-class (\`${GPT_SPARK}\`) with no closing authority.`,
    `- Frontier judgement (\`${GPT_FRONTIER}\`) is gated: use it only for final review or high-risk decisions with explicit authorization.`,
    "- Default reasoning effort is `middle`; raise to `high`/`xhigh` only for review or critical judgement.",
    "- State the full task, intent, and constraints up front in one turn; avoid drip-fed instructions.",
    "",
    "## Discipline",
    "",
    "- Separate creation from judgement: review with a different runtime/model family than the author when feasible.",
    "- No completion claim without tests or explicit verification evidence.",
    "- Stage explicit files only; never rewrite or discard another runtime's commits.",
    "",
    "Project-owned instructions outside this managed block remain consumer-owned.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# UT-TDD Agent Harness Shared Context",
    "",
    "Use repository-local UT-TDD commands for harness state and delegation.",
    "",
    "- `ut-tdd status` reports the local runtime mode.",
    "- `ut-tdd doctor --profile consumer-setup-smoke` runs consumer-safe setup and hook checks.",
    "- `ut-tdd doctor --profile consumer-toolchain` runs consumer-safe toolchain checks.",
    "- Full `ut-tdd doctor` is for source/governance repositories with PLAN/design/test-design artifacts.",
    "- `ut-tdd handover` reads and writes cross-runtime handover state.",
    '- `ut-tdd codex --role <role> --task "..."` delegates to Codex.',
    '- `ut-tdd claude --role <role> --task "..."` delegates to Claude.',
    "",
    "## Model routing defaults",
    "",
    "Route work to the cheapest model class that can own the outcome; reserve frontier",
    "models for judgement.",
    "",
    "| Model class | Default use | Effort |",
    "|---|---|---|",
    `| Claude Opus (\`${CLAUDE_OPUS}\`) | final review, judgement gates, hardest design decisions | high / xhigh |`,
    `| Claude Sonnet (\`${CLAUDE_SONNET}\`) | docs, design, UI/UX, structured review | high (xhigh for UI/UX) |`,
    `| Claude Haiku (\`${CLAUDE_HAIKU}\`) | scouting, triage, lightweight parallel checks | high, small scoped tasks |`,
    `| GPT/Codex workers (\`${GPT_WORKER}\` / \`${GPT_SPARK}\`) | implementation lanes | middle |`,
    `| GPT frontier (\`${GPT_FRONTIER}\`) | gated top-tier review/consultation | high / xhigh |`,
    "",
    "- Give agents the full goal, constraints, and done-criteria in the first turn.",
    "- Separate creation from judgement: prefer a different model family for review.",
    "- No completion claim without tests or explicit verification evidence.",
    "",
    "Do not put secrets, tokens, or machine-local absolute paths in adapter docs.",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/CLAUDE.md": [
    "<!-- UT-TDD:managed:start -->",
    "# Claude Runtime Adapter",
    "",
    "Claude Code sessions should route harness lifecycle work through `ut-tdd`.",
    "Consumer-owned Claude instructions can be added outside this managed block.",
    "",
    "- Session evidence: `ut-tdd status` and `ut-tdd handover`",
    "- Health check: `ut-tdd doctor --profile consumer-setup-smoke`",
    "- Toolchain check: `ut-tdd doctor --profile consumer-toolchain`",
    "- Review separation: use another runtime/model family when feasible",
    "",
    "## Claude subagent defaults",
    "",
    "- Always pass an explicit `model` when spawning subagents; it must match the",
    "  agent frontmatter family (opus / sonnet / haiku).",
    `- Opus (\`${CLAUDE_OPUS}\`) = judgement and final review; Sonnet (\`${CLAUDE_SONNET}\`) =`,
    `  docs/design/structured review; Haiku (\`${CLAUDE_HAIKU}\`) = scouting and triage.`,
    "- Claude-family reasoning effort defaults to `high`; use `xhigh` only for",
    "  high-judgement review or UI/UX work.",
    "- Give the full task specification up front; report findings with file and",
    "  command evidence before summaries.",
    "",
    "<!-- UT-TDD:managed:end -->",
    "",
  ].join("\n"),
  "adapter/.claude/settings.json": [
    "{",
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "Agent|Task",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("agent-guard")}",`,
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "Edit|Write|MultiEdit",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("work-guard")}",`,
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("session-start")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "Edit|Write|MultiEdit|Bash",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("post-tool-use")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("session-summary")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SubagentStop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("subagent-stop")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "agent-slots: release oldest guard slot (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.codex/config.toml": ["[features]", "hooks = true", ""].join("\n"),
  "adapter/.codex/hooks.json": [
    "{",
    '  "$comment": "UT-TDD Codex adapter hooks. Hosted/API tool surfaces still require explicit `ut-tdd guard preflight` before edits because repo-local Codex hooks do not execute there.",',
    '  "hooks": {',
    '    "PreToolUse": [',
    "      {",
    '        "matcher": "spawn_agent|spawn_agents_on_csv",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("agent-guard")}",`,
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "agent-guard: Codex subagent allowlist/model enforcement"',
    "          }",
    "        ]",
    "      },",
    "      {",
    '        "matcher": "apply_patch|write_file",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("work-guard")}",`,
    '            "timeout": 5,',
    '            "blockOnFailure": true,',
    '            "statusMessage": "work-guard: foreign edit protection"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "SessionStart": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("session-start")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: session start (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "PostToolUse": [',
    "      {",
    '        "matcher": "apply_patch|write_file|exec_command|local_shell",',
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("post-tool-use")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: post tool use (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ],",
    '    "Stop": [',
    "      {",
    '        "hooks": [',
    "          {",
    '            "type": "command",',
    `            "command": "${wrapperHookCommand("session-summary")}",`,
    '            "timeout": 5,',
    '            "statusMessage": "session-log: PLAN digest summary (fail-open)"',
    "          }",
    "        ]",
    "      }",
    "    ]",
    "  }",
    "}",
    "",
  ].join("\n"),
  "adapter/.claude/commands/ut-tdd-status.md": [
    "---",
    "description: Show UT-TDD status and consumer-safe doctor output",
    "---",
    "",
    "Run `ut-tdd status --json`, `ut-tdd doctor --profile consumer-setup-smoke`, and `ut-tdd doctor --profile consumer-toolchain`, then summarize mode, setup/hook health, toolchain health, active drafts, and open defers. Use full `ut-tdd doctor` only in source/governance repositories with PLAN/design/test-design artifacts.",
    "",
  ].join("\n"),
  "adapter/.claude/commands/ut-tdd-test.md": [
    "---",
    "description: Run UT-TDD verification for the current change",
    'argument-hint: "<changed area or PLAN id>"',
    "---",
    "",
    "Target: $ARGUMENTS",
    "",
    "Run the narrow Vitest target first, then `bun run typecheck`, `bun run lint`, `ut-tdd doctor --profile consumer-setup-smoke`, and `ut-tdd doctor --profile consumer-toolchain` for generated adapter/setup and consumer-safe toolchain health. Use full `ut-tdd doctor` only in source/governance repositories with PLAN/design/test-design artifacts.",
    "",
  ].join("\n"),
  "common/harness-check.yml": [
    "name: harness-check",
    "on:",
    "  push:",
    "    branches: [main]",
    "  pull_request:",
    "    branches: [main]",
    "jobs:",
    "  harness-check:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - uses: oven-sh/setup-bun@v2",
    "      - run: bun install --frozen-lockfile",
    "      - name: branch-type guard",
    "        env:",
    "          HEAD_REF: $" + "{{ github.head_ref || github.ref_name }}",
    "          BASE_REF: $" + "{{ github.base_ref || 'main' }}",
    "          PR_TITLE: $" +
      "{{ github.event.pull_request.title || github.event.head_commit.message || '' }}",
    "          PR_BODY: $" + "{{ github.event.pull_request.body || '' }}",
    "        run: |",
    "          printf '%s\\n' \"$PR_BODY\" > .ut-tdd-pr-body.txt",
    "          git log --format=%s -n 20 > .ut-tdd-commit-subjects.txt",
    '          bun .ut-tdd/bin/ut-tdd.mjs github guard --head-ref "$HEAD_REF" --base-ref "$BASE_REF" --pr-title "$PR_TITLE" --pr-body-file .ut-tdd-pr-body.txt --commit-file .ut-tdd-commit-subjects.txt',
    "      - run: bun run typecheck",
    "      - run: bun run test",
    "      - run: bun .ut-tdd/bin/ut-tdd.mjs audit quality --include-tests --limit 20",
    "      # Consumer CI gate is doctor --setup-smoke: full doctor asserts source-repo",
    "      # self-application state (design docs / PLAN corpus) and is structurally red",
    "      # on a fresh consumer repository (A-172 C-1).",
    "      - run: bun .ut-tdd/bin/ut-tdd.mjs doctor --setup-smoke",
    "",
  ].join("\n"),
  "common/commitlint.config.js":
    "module.exports = { extends: ['@commitlint/config-conventional'] };\n",
  "common/escalation-stale.yml": [
    "name: escalation-stale",
    "on:",
    "  schedule:",
    "    - cron: '0 0 * * 1'",
    "jobs:",
    "  noop:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - run: echo escalation policy placeholder",
    "",
  ].join("\n"),
  "common/recovery.md":
    "# Recovery\n\nDescribe the broken invariant, evidence, and rollback path.\n",
  "common/add-feature.md":
    "# Add Feature\n\nDescribe objective, scope, tests, and review evidence.\n",
  "common/PULL_REQUEST_TEMPLATE.md":
    "## Summary\n\n## Verification\n\n## Review evidence\n\nCloses #\n",
  "team/CODEOWNERS": [
    "* {{TL_TEAM}}",
    "/docs/ {{PO_TEAM}}",
    "/src/ {{TL_TEAM}}",
    "/tests/ {{QA_TEAM}}",
    "",
  ].join("\n"),
  "team/setup-branch-protection.sh": [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    'REPO="$' + '{1:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"',
    'echo "Apply branch protection to $' + '{REPO}/main"',
    'read -r -p "Continue? [y/N] " ans',
    '[[ "$' + '{ans}" == "y" || "$' + '{ans}" == "Y" ]] || exit 1',
    'gh api -X PUT "repos/$' + '{REPO}/branches/main/protection" \\',
    '  -H "Accept: application/vnd.github+json" \\',
    "  --input - <<'JSON'",
    "{",
    '  "required_status_checks": { "strict": true, "checks": [ { "context": "harness-check" } ] },',
    '  "enforce_admins": true,',
    '  "required_pull_request_reviews": { "required_approving_review_count": 1 },',
    '  "restrictions": null',
    "}",
    "JSON",
    "",
  ].join("\n"),
};

export const COMMON_FILES: { template: string; file: GeneratedFile }[] = [
  {
    template: "common/ut-tdd.mjs",
    file: {
      path: join(".ut-tdd", "bin", "ut-tdd.mjs"),
      category: "A",
      purpose: "Project-local UT-TDD hook wrapper",
    },
  },
  {
    template: "adapter/AGENTS.md",
    file: {
      path: "AGENTS.md",
      category: "A",
      purpose: "UT-TDD adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/CLAUDE.md",
    file: {
      path: "CLAUDE.md",
      category: "A",
      purpose: "UT-TDD shared adapter context (managed block)",
    },
  },
  {
    template: "adapter/.codex/config.toml",
    file: {
      path: join(".codex", "config.toml"),
      category: "A",
      purpose: "Codex project-local hook enablement",
    },
  },
  {
    template: "adapter/.codex/hooks.json",
    file: {
      path: join(".codex", "hooks.json"),
      category: "A",
      purpose: "Codex hook settings for UT-TDD CLI entrypoints",
    },
  },
  {
    template: "adapter/.claude/CLAUDE.md",
    file: {
      path: join(".claude", "CLAUDE.md"),
      category: "A",
      purpose: "Claude runtime adapter instructions (managed block)",
    },
  },
  {
    template: "adapter/.claude/settings.json",
    file: {
      path: join(".claude", "settings.json"),
      category: "A",
      purpose: "Claude hook settings for UT-TDD CLI entrypoints",
    },
  },
  ...CLAUDE_AGENT_FILES,
  ...CLAUDE_COMMAND_FILES,
  {
    template: "adapter/.claude/commands/ut-tdd-status.md",
    file: {
      path: join(".claude", "commands", "ut-tdd-status.md"),
      category: "A",
      purpose: "Claude slash command for UT-TDD status checks",
    },
  },
  {
    template: "adapter/.claude/commands/ut-tdd-test.md",
    file: {
      path: join(".claude", "commands", "ut-tdd-test.md"),
      category: "A",
      purpose: "Claude slash command for UT-TDD verification",
    },
  },
  {
    template: "common/harness-check.yml",
    file: {
      path: join(".github", "workflows", "harness-check.yml"),
      category: "A",
      purpose: "CI (typecheck + regression)",
    },
  },
  {
    template: "common/commitlint.config.js",
    file: { path: "commitlint.config.js", category: "A", purpose: "Conventional Commits" },
  },
  {
    template: "common/escalation-stale.yml",
    file: {
      path: join(".github", "workflows", "escalation-stale.yml"),
      category: "A",
      purpose: "stale escalation issue workflow",
    },
  },
  {
    template: "common/recovery.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "recovery.md"),
      category: "A",
      purpose: "Recovery issue template",
    },
  },
  {
    template: "common/add-feature.md",
    file: {
      path: join(".github", "ISSUE_TEMPLATE", "add-feature.md"),
      category: "A",
      purpose: "Add-feature issue template",
    },
  },
  {
    template: "common/PULL_REQUEST_TEMPLATE.md",
    file: {
      path: join(".github", "PULL_REQUEST_TEMPLATE.md"),
      category: "A",
      purpose: "PR template",
    },
  },
];
