import type { TableDef } from "./harness-db";
import { col, pk } from "./harness-db-table-builders";

export const HARNESS_DB_CORE_TABLES: TableDef[] = [
  // --- §2.7 基本 7 ---
  {
    name: "plan_registry",
    columns: [
      pk("plan_id"),
      col("kind"),
      col("layer"),
      col("sub_doc"),
      col("drive"),
      col("status"),
      col("parent"),
      col("updated_at"),
      // decision_outcome: S4 verdict for PoC (kind=poc) PLANs.
      // Values: "confirmed" | "rejected" | "pivot" | "" (null/unset stored as "").
      // Source: PLAN frontmatter field `decision_outcome`. Used by projectPocEvaluations (FR-L1-43).
      col("decision_outcome"),
      // source_hash: sha256 of the full PLAN markdown content. Used by drive-db-registration to
      // detect persisted harness.db staleness even when the plan count is unchanged.
      col("source_hash"),
    ],
  },
  {
    name: "artifact_registry",
    columns: [
      pk("artifact_id"),
      col("artifact_type"),
      col("path"),
      col("pair_artifact"),
      col("status"),
      col("updated_at"),
    ],
  },
  {
    name: "model_runs",
    columns: [
      pk("run_id"),
      col("runtime"),
      col("model"),
      col("role"),
      col("drive"),
      col("plan_id"),
      col("started_at"),
      col("completed_at"),
      col("evidence_path"),
      // FR-L1-38 token telemetry (PLAN-L7-57): cross-runtime per-run usage. NULL for review-evidence
      // 由来の行 (token 不明)、token-tracker が session ログ走査で投入した行のみ非 NULL。
      // cached_input/reasoning は runtime により欠ける (Claude=cache_read, Codex=cached_input/reasoning)。
      col("input_tokens", "INTEGER"),
      col("output_tokens", "INTEGER"),
      col("cached_input_tokens", "INTEGER"),
      col("reasoning_tokens", "INTEGER"),
      // cost_usd: provider 非対称の enrichment。Claude=CLAUDE_PRICING で計算可、Codex=OpenAI 単価
      // source 未取得のため NULL (core metric は token 効率、$ は出せる runtime のみ)。
      col("cost_usd", "REAL"),
    ],
  },
  {
    name: "trace_edges",
    columns: [
      pk("edge_id"),
      col("from_artifact"),
      col("to_artifact"),
      col("edge_kind"),
      col("plan_id"),
      col("status"),
    ],
  },
  {
    name: "coverage",
    columns: [
      pk("coverage_id"),
      col("scope"),
      col("subject_id"),
      col("metric"),
      col("value", "REAL"),
      col("threshold", "REAL"),
      col("status"),
    ],
  },
  {
    name: "findings",
    columns: [
      pk("finding_id"),
      col("kind"),
      col("severity"),
      col("subject_id"),
      col("source"),
      col("status"),
      col("evidence_path"),
    ],
  },
  {
    name: "gate_runs",
    columns: [
      pk("gate_run_id"),
      col("gate_id"),
      col("plan_id"),
      col("status"),
      col("checked_at"),
      col("evidence_path"),
    ],
  },
  // --- §9.1 Reference-Feedback 拡張 10 ---
  {
    name: "drive_runs",
    columns: [
      pk("drive_run_id"),
      col("plan_id"),
      col("session_id"),
      col("drive"),
      col("mode"),
      col("layer"),
      col("kind"),
      col("started_at"),
      col("completed_at"),
      col("status"),
    ],
  },
  {
    name: "hook_events",
    columns: [
      pk("event_id"),
      col("session_id"),
      col("plan_id"),
      col("hook_name"),
      col("event_type"),
      col("occurred_at"),
      col("digest"),
      col("evidence_path"),
    ],
  },
  {
    name: "skill_invocations",
    columns: [
      pk("skill_invocation_id"),
      col("session_id"),
      col("plan_id"),
      col("skill_id"),
      col("layer"),
      col("drive"),
      col("fired_at"),
      col("source"),
      col("accepted", "INTEGER"),
    ],
  },
  {
    name: "skill_recommendations",
    columns: [
      pk("skill_recommendation_id"),
      col("session_id"),
      col("plan_id"),
      col("skill_id"),
      col("rank", "INTEGER"),
      col("score", "REAL"),
      col("reason"),
      col("recommended_at"),
    ],
  },
  {
    name: "feedback_events",
    columns: [
      pk("feedback_event_id"),
      col("finding_id"),
      col("plan_id"),
      col("source_table"),
      col("source_id"),
      col("source_color"),
      col("signal_type"),
      col("severity"),
      col("status"),
      col("next_action"),
      col("created_at"),
    ],
  },
  {
    name: "memory_entries",
    columns: [
      pk("memory_id"),
      col("kind"),
      col("title"),
      col("body"),
      col("tags"),
      col("source_path"),
      col("updated_at"),
      col("content_hash"),
    ],
  },
  {
    name: "quality_signals",
    columns: [
      pk("signal_id"),
      col("source"),
      col("subject_id"),
      col("metric"),
      col("value", "REAL"),
      col("threshold", "REAL"),
      col("status"),
      col("computed_at"),
    ],
  },
  {
    name: "test_runs",
    columns: [
      pk("test_run_id"),
      col("session_id"),
      col("plan_id"),
      col("command"),
      col("runner"),
      col("runtime"),
      col("os"),
      col("shell"),
      col("scope"),
      col("started_at"),
      col("completed_at"),
      col("exit_code", "INTEGER"),
      col("evidence_path"),
      col("output_digest"),
      col("green_definition_id"),
      col("status"),
    ],
  },
  {
    name: "test_cases",
    columns: [
      pk("test_case_id"),
      col("test_run_id"),
      col("test_file"),
      col("test_name"),
      col("plan_id"),
      col("fr_id"),
      col("artifact_id"),
      col("kind"),
      col("oracle_id"),
      col("name"),
      col("first_seen_at"),
      col("last_seen_at"),
      col("status"),
      col("duration_ms", "REAL"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_results",
    columns: [
      pk("test_result_id"),
      col("test_case_id"),
      col("test_run_id"),
      col("oracle_id"),
      col("status"),
      col("duration_ms", "REAL"),
      col("failure_digest"),
      col("started_at"),
      col("completed_at"),
      col("message"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_artifact_edges",
    columns: [
      pk("edge_id"),
      col("test_artifact_edge_id"),
      col("test_case_id"),
      col("test_run_id"),
      col("artifact_id"),
      col("plan_id"),
      col("source_path"),
      col("artifact_path"),
      col("edge_kind"),
      col("oracle_id"),
      col("evidence_path"),
    ],
  },
  {
    name: "test_flake_events",
    columns: [
      pk("flake_event_id"),
      col("test_case_id"),
      col("window"),
      col("pass_count", "INTEGER"),
      col("fail_count", "INTEGER"),
      col("flake_score", "REAL"),
      col("computed_at"),
      col("evidence_path"),
    ],
  },
  {
    name: "search_index",
    columns: [
      pk("search_id"),
      col("subject_type"),
      col("subject_id"),
      col("path"),
      col("title"),
      col("tokens"),
      col("summary"),
      col("updated_at"),
    ],
  },
  {
    name: "workflow_runs",
    columns: [
      pk("workflow_run_id"),
      col("plan_id"),
      col("drive_run_id"),
      col("workflow"),
      col("phase"),
      col("ready_status"),
      col("blocked_reason"),
      col("human_required", "INTEGER"),
      col("checked_at"),
    ],
  },
  {
    name: "guardrail_decisions",
    columns: [
      pk("guardrail_decision_id"),
      col("plan_id"),
      col("session_id"),
      col("guardrail"),
      col("decision"),
      col("mode"),
      col("human_signoff_required", "INTEGER"),
      col("evidence_path"),
      col("decided_at"),
    ],
  },
  {
    name: "issue_queue",
    columns: [
      pk("issue_queue_id"),
      col("source_event_id"),
      col("plan_id"),
      col("target"),
      col("title"),
      col("body"),
      col("status"),
      col("human_approval_required", "INTEGER"),
      col("approved_by"),
      col("approved_at"),
      col("external_issue_id"),
      col("external_issue_url"),
      col("created_at"),
    ],
  },
  {
    name: "trouble_events",
    columns: [
      pk("trouble_event_id"),
      col("source_event_id"),
      col("plan_id"),
      col("category"),
      col("severity"),
      col("summary"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "retry_events",
    columns: [
      pk("retry_event_id"),
      col("plan_id"),
      col("workflow"),
      col("phase"),
      col("attempt_count", "INTEGER"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "improvement_log",
    columns: [
      pk("improvement_log_id"),
      col("source_event_id"),
      col("plan_id"),
      col("category"),
      col("summary"),
      col("next_action"),
      col("status"),
      col("created_at"),
    ],
  },
  {
    name: "automation_assets",
    columns: [
      pk("asset_id"),
      col("asset_type"),
      col("path"),
      col("trigger"),
      col("role"),
      col("capability"),
      col("skill_type"),
      col("category"),
      col("applies_layers"),
      col("applies_drive_models"),
      col("drift_status"),
      col("indexed_at"),
    ],
  },
];
