import type { TableDef } from "./harness-db.ts";
import { col, enumCheck, foreignKey, pk, requiredCol } from "./harness-db-table-builders.ts";

export const HARNESS_DB_SPEC_IR_TABLES: TableDef[] = [
  {
    name: "spec_defs",
    columns: [
      pk("spec_id"),
      col("spec_kind"),
      col("layer"),
      col("sub_doc"),
      col("owner_artifact_id"),
      col("owner_path"),
      col("section_anchor"),
      col("title"),
      col("lifecycle_status"),
      col("plan_id"),
      col("source_path"),
      col("source_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "spec_relations",
    columns: [
      pk("relation_id"),
      col("from_spec_id"),
      col("to_spec_id"),
      col("relation_kind"),
      col("plan_id"),
      col("status"),
      col("source"),
      col("evidence_path"),
      col("indexed_at"),
    ],
  },
  {
    name: "schedule_entries",
    columns: [
      pk("schedule_entry_id"),
      col("plan_id"),
      col("layer"),
      col("sub_doc"),
      col("v_pair"),
      col("predecessor_plan_ids"),
      col("current_location"),
      col("rag"),
      col("status"),
      col("blocked_reason"),
      col("source_path"),
      col("plan_revision"),
      col("source_hash"),
      col("indexed_at"),
    ],
  },
  {
    name: "activation_entries",
    columns: [
      pk("activation_entry_id"),
      col("profile_id"),
      col("target_kind"),
      col("target_id"),
      col("scope_status"),
      col("target_version"),
      col("defer_reason"),
      col("enabled", "INTEGER"),
      col("source_path"),
      col("plan_id"),
      col("indexed_at"),
    ],
  },
  {
    name: "activation_schedule_reviews",
    columns: [
      pk("activation_schedule_review_id"),
      col("profile_id"),
      col("plan_id"),
      col("schedule_entry_id"),
      col("activation_entry_id"),
      col("target_kind"),
      col("target_id"),
      col("scope_status"),
      col("enabled", "INTEGER"),
      col("target_version"),
      col("defer_reason"),
      col("current_location"),
      col("rag"),
      col("schedule_status"),
      col("layer"),
      col("sub_doc"),
      col("v_pair"),
      col("source_path"),
      col("indexed_at"),
    ],
  },
  {
    name: "document_catalog_entries",
    columns: [
      pk("document_catalog_entry_id"),
      col("doc_type_id"),
      col("layer"),
      col("sub_doc"),
      col("category"),
      col("requirement_class"),
      col("applicability"),
      col("default_status"),
      col("source_doc_family"),
      col("authoring_source_path"),
      col("projection_table"),
      col("profile_controlled", "INTEGER"),
      col("skip_reason_required", "INTEGER"),
      col("source_path"),
      col("indexed_at"),
    ],
    unique: [["doc_type_id"]],
  },
  {
    name: "document_scale_profile_entries",
    columns: [
      pk("document_scale_profile_entry_id"),
      requiredCol("profile_id"),
      requiredCol("doc_type_id"),
      requiredCol("decision"),
      requiredCol("detail_override"),
      requiredCol("status_override"),
      requiredCol("reason"),
      col("required_plan_id"),
      requiredCol("row_digest"),
      requiredCol("source_path"),
      requiredCol("indexed_at"),
    ],
    unique: [["profile_id", "doc_type_id"]],
    foreignKeys: [
      foreignKey(["profile_id"], { table: "document_scale_profiles", columns: ["profile_id"] }),
      foreignKey(["doc_type_id"], { table: "document_catalog_entries", columns: ["doc_type_id"] }),
    ],
    checks: [
      enumCheck("decision", ["adopt", "conditional", "skip", "defer"]),
      enumCheck("detail_override", ["lite", "standard", "detailed"]),
      enumCheck("status_override", [
        "minimal",
        "standard",
        "required",
        "profile_controlled",
        "skipped",
      ]),
      {
        kind: "or",
        expressions: [
          {
            kind: "not",
            expression: { kind: "compare", column: "decision", operator: "=", value: "defer" },
          },
          { kind: "is-null", column: "required_plan_id", negate: true },
        ],
      },
    ],
  },
  {
    name: "document_scale_profile_reviews",
    columns: [
      pk("document_scale_profile_review_id"),
      col("profile_id"),
      col("doc_type_id"),
      col("document_scale_profile_entry_id"),
      col("document_catalog_entry_id"),
      col("decision"),
      col("detail_override"),
      col("status_override"),
      col("reason"),
      col("required_plan_id"),
      col("catalog_layer"),
      col("catalog_sub_doc"),
      col("requirement_class"),
      col("catalog_default_status"),
      col("catalog_profile_controlled", "INTEGER"),
      col("catalog_skip_reason_required", "INTEGER"),
      col("source_path"),
      col("indexed_at"),
    ],
  },
  {
    name: "spec_rag_closure_entries",
    columns: [
      pk("spec_rag_entry_id"),
      col("spec_id"),
      col("spec_kind"),
      col("layer"),
      col("sub_doc"),
      col("rag"),
      col("closure_status"),
      col("requires_test", "INTEGER"),
      col("upstream_count", "INTEGER"),
      col("downstream_count", "INTEGER"),
      col("test_count", "INTEGER"),
      col("finding_count", "INTEGER"),
      col("impact_summary"),
      col("source_path"),
      col("indexed_at"),
    ],
  },
  {
    name: "detector_route_candidates",
    columns: [
      pk("route_candidate_id"),
      col("source_table"),
      col("source_id"),
      col("detector_id"),
      col("finding_kind"),
      col("severity"),
      col("subject_kind"),
      col("subject_id"),
      col("filing_target_id"),
      col("target_layer"),
      col("target_sub_doc"),
      col("candidate_status"),
      col("reason"),
      col("evidence_path"),
      col("computed_at"),
    ],
  },
  {
    name: "agent_contracts",
    columns: [
      pk("agent_contract_id"),
      col("target_path"),
      col("defines"),
      col("read_first"),
      col("done_when"),
      col("source_path"),
      col("source_hash"),
      col("indexed_at"),
    ],
  },
];
